# Generated by Django 2.0.7 on 2018-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redback_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rb_item',
            name='archiJson',
            field=models.TextField(default={'name': 'hello world'}, max_length=99999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rb_item',
            name='displayGeom',
            field=models.TextField(blank=True, max_length=99999, null=True),
        ),
    ]
