# Generated by Django 2.0.7 on 2018-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redback_api', '0002_auto_20180828_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='rb_item',
            name='description',
            field=models.CharField(default={'description': 'helloworld description'}, max_length=150),
            preserve_default=False,
        ),
    ]
